name: flutter_basics
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # preference
  shared_preferences: ^0.4.2

  # event - bus
  event_bus: ^1.1.0

  # toast
  fluttertoast: ^3.0.4

  # redux 状态管理
  flutter_redux: ^0.5.3

  # 系统自带组件的国际化
  flutter_localizations:
    sdk: flutter

  # flutter login: 
  # https://flutterawesome.com/a-new-open-source-flutter-login-home-animation/
  flutter_login: ^1.0.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # 登录按钮
  rounded_loading_button: ^1.0.0

  # Bottom Navigation Bar
  #ff_navigation_bar: ^0.0.1

  # Alert
  # https://flutterawesome.com/xustomizable-and-easy-to-use-alert-popup-dialogs-for-flutter/
  rflutter_alert: ^1.0.2

  # HUD
  # https://flutterawesome.com/a-light-weight-package-to-show-progress-dialog/
  progress_dialog: ^1.1.0+1

  # 网络请求
  #  https://github.com/flutterchina/dio
  dio: ^3.0.9

  #  轮播banner
  #  https://pub:dev/packages/flutter_swiper
  flutter_swiper: ^1.1.6

  #  下拉刷新上拉加载
  #https://github.com/xuelongqy/flutter_easyrefresh
  flutter_easyrefresh: ^2.1.0

  # 徽章
  #https://github.com/yako-dev/flutter_badges
  badges: ^1.1.0

  # A library to draw fantastic charts in Flutter 图标控件
  #https://github.com/imaNNeoFighT/fl_chart
  fl_chart: ^0.8.3

  # WebView插件 https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: 0.3.19+9

  # 路由框架 https://github.com/theyakka/fluro
  fluro: ^1.6.1

  #  尺寸适配
  # https://github.com/OpenFlutter/flutter_screenutil
  flutter_screenutil: ^1.0.2

  #  The Reactive Extensions for Dart
  #https://github.com/ReactiveX/rxdart
  rxdart: ^0.23.1

  #工具类
  #https://github.com/Sky24n/flustars
  flustars: ^0.2.6+1

  #  状态管理
  provider: ^4.0.4

  #图片选择器
  #https://pub.dev/packages/image_picker
  image_picker: 0.6.3+4

  cached_network_image: ^2.0.0

  # Page loading placeholder
  # https://github.com/hnvn/flutter_shimmer
  shimmer: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/template_background_image.png
    - assets/jsons/local_basic_config.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
